{% set name = "bioimageio.core" %}
{% set version = "0.9.3" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/bioimageio_core-{{ version }}.tar.gz
  sha256: 0ece1b65a88246cc87733a0a8ba5e27380800c81dfe33610ca10a086bf4b8dec

build:
  number: 0
  noarch: python
  entry_points:
    - bioimageio = bioimageio.core.__main__:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - bioimageio.spec ==0.5.5.5
    - h5py
    - imagecodecs
    - imageio >=2.10
    - loguru
    - numpy
    - pydantic-settings >=2.5,<3
    - pydantic >=2.7.0,<3
    - python >={{ python_min }}
    - ruyaml
    - scipy
    - tqdm
    - typing-extensions
    - xarray >=2023.01,<2025.3.0

test:
  imports:
    - bioimageio
    - bioimageio.core
  commands:
    - pip check
    - bioimageio --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/bioimage-io/python-bioimage-io
  summary: Python functionality for the bioimage model zoo
  dev_url: https://github.com/bioimage-io/python-bioimage-io
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - constantinpape
    - FynnBe
    - k-dominik
    - oeway
