{% set name = "bioimageio.core" %}
{% set version = "0.6.7" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/bioimageio.core-{{ version }}.tar.gz
  sha256: 834a8bc0eb46be567d63eecdfc8942b0551f55884c617fac867b227bb14d157e

build:
  number: 0
  noarch: python
  entry_points:
    - bioimageio = bioimageio.core.__main__:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - bioimageio.spec ==0.5.2.*
    - fire
    - imageio >=2.5
    - loguru
    - numpy
    - pydantic-settings
    - pydantic
    - python-dotenv
    - python >=3.8
    - requests
    - ruyaml
    - tqdm
    - typing-extensions
    - xarray

test:
  imports:
    - bioimageio
    - bioimageio.core
  commands:
    - pip check
    - bioimageio --help
  requires:
    - pip

about:
  home: https://github.com/bioimage-io/python-bioimage-io
  summary: Python functionality for the bioimage model zoo
  dev_url: https://github.com/bioimage-io/python-bioimage-io
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - constantinpape
    - FynnBe
    - k-dominik
    - oeway
