{% set name = "bioimageio.core" %}
{% set version = "0.7.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/bioimageio.core-{{ version }}.tar.gz
  sha256: ed7c7fb70987be6aaa6ad1c5febefb54d179129c560873ae93e7abdc69aa09a2

build:
  number: 0
  noarch: python
  entry_points:
    - bioimageio = bioimageio.core.__main__:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
    - setuptools
  run:
    - bioimageio.spec ==0.5.3.5
    - h5py
    - imageio >=2.10
    - loguru
    - numpy
    - pydantic-settings >=2.7.0,<3
    - pydantic
    - python >=3.8
    - requests
    - ruyaml
    - tqdm
    - typing-extensions
    - xarray

test:
  imports:
    - bioimageio
    - bioimageio.core
  commands:
    - pip check
    - bioimageio --help
  requires:
    - pip

about:
  home: https://github.com/bioimage-io/python-bioimage-io
  summary: Python functionality for the bioimage model zoo
  dev_url: https://github.com/bioimage-io/python-bioimage-io
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - constantinpape
    - FynnBe
    - k-dominik
    - oeway
